#!/bin/bash
#Write a script which delete an ACTIVE user on the VM.
users=$(users)
me=$(whoami)
echo "-----------------------------------"
echo "Welcome to deleting an active user!"
echo ""
echo "These are the users:"
echo $users
echo ""
echo "Write the name of the user you wish to delete or write exit to exit"
read username
echo ""


check=$(getent passwd {1000..60000} | cut -d : -f 1 | grep -w $username)
if [ "$username" == "exit" ]; then
		echo "Exiting, bye!"
		exit 1
fi
if [ "$check" != "$NULL" ]; then
		if [ "$check" == "$me" || "$check" == "root" ]; then
			echo "You can't delete yourself or root, choose another user next time"
		else
			sudo userdel -rf $username
			echo "User deleted"
		fi
else
	echo "User doesn't exist"
fi