#!/bin/bash
#Write a script which delete an ACTIVE user on the VM.
users=$(users)
me=$(whoami)
echo "-----------------------------------"
echo "Welcome to deleting an active user!"
echo ""
echo "These are the users:"
awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd
echo ""
echo "Write the name of the user you wish to delete or write exit to exit"
read username
echo ""


check=$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | grep -w $username)
if [ "$username" == "exit" ]; then
		echo "Exiting, bye!"
		exit 1
fi
if [ "$check" != "$NULL" ]; then
		sudo userdel -rf $username
		echo "User deleted"
else
	echo "User doesn't exist"
fi