#!/bin/bash

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

clear

echo
echo
echo -e "-:-:-:-:-:-:-:-"
echo -e "|   ${BIRed}WELCOME${Color_Off}   |"
echo -e "|      ${BIRed}TO${Color_Off}     |"
echo -e "|     ${BIRed}THE${Color_Off}     |"
echo -e "|  ${BIRed}Script 03${Color_Off}  |"
echo -e "|     ${BIBlack}AKA${Color_Off}     |"
echo -e "|  ${BIRed}The tester${Color_Off} |"
echo -e "-:-:-:-:-:-:-:-"
echo
echo
echo -e "${BIPurple}Choose what to test!${Color_Off}"
echo
echo -e "${Purple}(Type the name of the section to "
echo -e "${Purple}to see questions and answers)"
echo
echo -e "${Yellow}Network"
echo -e "01  02a  02b  03  04  05  06  07"
echo -e "08  09   10   11  12  13  15${Color_Off}"
echo
echo
echo -e "${Green}System"
echo -e "01  02  03  04  05  06  07  08  09  10  11  12"
echo -e "13  14  15  16  17  18  19  20  21  22  23  24${Color_Off}"
echo
echo -e "${UCyan}Type exit to exit${Color_Off}"
echo

while :
do
read  -p "Type here: " selected
if [ "$selected" == "exit" ]; then
	echo
	echo -e "${UCyan}Sad to see you go, bye!${Color_Off}"
	echo
	exit 1
else
	if [ "$selected" == "Network" ] || [ "$selected" == "network" ]; then
		echo
		echo -e "${BYellow}Network selected!${Color_Off}"
		echo
	else
		if [ "$selected" == "System" ] || [ "$selected" == "system" ]; then
			echo
			echo -e "${BGreen}System selected!${Color_Off}"
			echo
		else
			echo
			echo -e "${Red}Invalid command, try again!${Color_Off}"
			echo
		fi
	fi
fi
case "$selected" in

"Network" | "network" )
echo -e "${Yellow}01"
cat ../network/01
echo
echo
echo -e "02a"
cat ../network/02a
echo
echo
echo -e "02b"
cat ../network/02b
echo
echo
echo -e "03"
cat ../network/03
echo
echo
echo -e "04"
cat ../network/04
echo
echo
echo -e "05"
cat ../network/05
echo
echo
echo -e "06"
cat ../network/06
echo
echo
echo -e "07"
cat ../network/07
echo
echo
echo -e "08"
cat ../network/08
echo
echo
echo -e "09"
cat ../network/09
echo
echo
echo -e "10"
cat ../network/10
echo
echo
echo -e "11"
cat ../network/11
echo
echo
echo -e "12"
cat ../network/12
echo
echo
echo -e "13"
cat ../network/13
echo
echo
echo -e "14"
cat ../network/14
echo
echo
echo -e "15"
cat ../network/15
echo
echo -e "${Color_Off}"
;;

"System" | "system" )
echo -e "${Green}01"
cat ../system/01
echo
echo
echo -e "02"
cat ../system/02
echo
echo
echo -e "03"
cat ../system/03
echo
echo
echo -e "04"
cat ../system/04
echo
echo
echo -e "05"
cat ../system/05
echo
echo
echo -e "06"
cat ../system/06
echo
echo
echo -e "07"
cat ../system/07
echo
echo
echo -e "08"
cat ../system/08
echo
echo
echo -e "09"
cat ../system/09
echo
echo
echo -e "10"
cat ../system/10
echo
echo
echo -e "11"
cat ../system/11
echo
echo
echo -e "12"
cat ../system/12
echo
echo
echo -e "13"
cat ../system/13
echo
echo
echo -e "14"
cat ../system/14
echo
echo
echo -e "15"
cat ../system/15
echo
echo
echo -e "16"
cat ../system/16
echo
echo
echo -e "17"
cat ../system/17
echo
echo
echo -e "18"
cat ../system/18
echo
echo
echo -e "19"
cat ../system/19
echo
echo
echo -e "20"
cat ../system/20
echo
echo
echo -e "21"
cat ../system/21
echo
echo
echo -e "22"
cat ../system/22
echo
echo
echo -e "23"
cat ../system/23
echo
echo
echo -e "24"
cat ../system/24
echo
echo -e "${Color_Off}"
;;

* )
echo -e "${Yellow}Network"
echo -e "01  02a  02b  03  04  05  06  07"
echo -e "08  09   10   11  12  13  15${Color_Off}"
echo
echo
echo -e "${Green}System"
echo -e "01  02  03  04  05  06  07  08  09  10  11  12"
echo -e "13  14  15  16  17  18  19  20  21  22  23  24${Color_Off}"
echo
echo -e "${UCyan}Type exit to exit${Color_Off}"
echo
;;

esac
done
