#!/bin/bash

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

clear

echo
echo
echo -e "-:-:-:-:-:-:-:-"
echo -e "|   ${BIRed}WELCOME${Color_Off}   |"
echo -e "|      ${BIRed}TO${Color_Off}     |"
echo -e "|     ${BIRed}THE${Color_Off}     |"
echo -e "|  ${BIRed}Script 03${Color_Off}  |"
echo -e "-:-:-:-:-:-:-:-"
echo
echo
echo -e "${BIPurple}Choose what to do!${Color_Off}"
echo
echo -e "${Purple}Type the name or number of the section to advance"
echo
echo -e "${Yellow}1 - Init answers"
echo
echo -e "${Blue}2 - System commands"
echo
echo -e "${IPurple}3 - A random joke"
echo
echo -e "${UCyan}Type exit to exit${Color_Off}"
echo

while :
do

read -p "Type here: " selected
if [ "$selected" == "exit" ]; then
	echo
	echo -e "${UCyan}Sad to see you go, bye!${Color_Off}"
	echo
	exit 1
else
	if [ "$selected" == "Init answers" ] || [ "$selected" == "init answers" ] || [ "$selected" == "init" ] || [ "$selected" == "Init" ] || [ "$selected" == "1" ] || [ "$selected" == "1 - Init answers" ]; then
		echo
		echo -e "${Yellow}Init answers"
		echo
		echo -e "${Purple}Type the name or number of the section to see the answers"
		echo
		echo -e "${Yellow}1 - Network"
		echo -e "01  02a  02b  03  04  05  06  07"
		echo -e "08  09   10   11  12  13  15${Color_Off}"
		echo
		echo
		echo -e "${Green}2 - System"
		echo -e "01  02  03  04  05  06  07  08  09  10  11  12"
		echo -e "13  14  15  16  17  18  19  20  21  22  23  24${Color_Off}"
		echo
		echo -e "${UCyan}Type exit to exit${Color_Off}"
		echo
		echo -e "${UCyan}Type menu to return to main menu${Color_Off}"
		echo

		while :
		do
		read  -p "Type here: " selected
		if [ "$selected" == "exit" ]; then
			echo
			echo -e "${UCyan}Sad to see you go, bye!${Color_Off}"
			echo
			exit 1
		else
			if [ "$selected" == "Network" ] || [ "$selected" == "network" ] || [ "$selected" == "1" ]; then
				echo
				echo -e "${BYellow}Network selected!${Color_Off}"
				echo
			else
				if [ "$selected" == "System" ] || [ "$selected" == "system" ] || [ "$selected" == "2" ]; then
					echo
					echo -e "${BGreen}System selected!${Color_Off}"
					echo
				else
					if [ "$selected" == "menu" ]; then
						./03
						exit 1
					else
						echo
						echo -e "${Red}Invalid command, try again!${Color_Off}"
						echo
					fi
				fi
			fi
		fi
		case "$selected" in

		"Network" | "network" | "1")
		echo -e "${Yellow}01"
		cat ../network/01
		echo
		echo
		echo -e "02a"
		cat ../network/02a
		echo
		echo
		echo -e "02b"
		cat ../network/02b
		echo
		echo
		echo -e "03"
		cat ../network/03
		echo
		echo
		echo -e "04"
		cat ../network/04
		echo
		echo
		echo -e "05"
		cat ../network/05
		echo
		echo
		echo -e "06"
		cat ../network/06
		echo
		echo
		echo -e "07"
		cat ../network/07
		echo
		echo
		echo -e "08"
		cat ../network/08
		echo
		echo
		echo -e "09"
		cat ../network/09
		echo
		echo
		echo -e "10"
		cat ../network/10
		echo
		echo
		echo -e "11"
		cat ../network/11
		echo
		echo
		echo -e "12"
		cat ../network/12
		echo
		echo
		echo -e "13"
		cat ../network/13
		echo
		echo
		echo -e "14"
		cat ../network/14
		echo
		echo
		echo -e "15"
		cat ../network/15
		echo
		echo -e "${Color_Off}"
		;;

		"System" | "system" | "2")
		echo -e "${Green}01"
		cat ../system/01
		echo
		echo
		echo -e "02"
		cat ../system/02
		echo
		echo
		echo -e "03"
		cat ../system/03
		echo
		echo
		echo -e "04"
		cat ../system/04
		echo
		echo
		echo -e "05"
		cat ../system/05
		echo
		echo
		echo -e "06"
		cat ../system/06
		echo
		echo
		echo -e "07"
		cat ../system/07
		echo
		echo
		echo -e "08"
		cat ../system/08
		echo
		echo
		echo -e "09"
		cat ../system/09
		echo
		echo
		echo -e "10"
		cat ../system/10
		echo
		echo
		echo -e "11"
		cat ../system/11
		echo
		echo
		echo -e "12"
		cat ../system/12
		echo
		echo
		echo -e "13"
		cat ../system/13
		echo
		echo
		echo -e "14"
		cat ../system/14
		echo
		echo
		echo -e "15"
		cat ../system/15
		echo
		echo
		echo -e "16"
		cat ../system/16
		echo
		echo
		echo -e "17"
		cat ../system/17
		echo
		echo
		echo -e "18"
		cat ../system/18
		echo
		echo
		echo -e "19"
		cat ../system/19
		echo
		echo
		echo -e "20"
		cat ../system/20
		echo
		echo
		echo -e "21"
		cat ../system/21
		echo
		echo
		echo -e "22"
		cat ../system/22
		echo
		echo
		echo -e "23"
		cat ../system/23
		echo
		echo
		echo -e "24"
		cat ../system/24
		echo
		echo -e "${Color_Off}"
		;;

		* )
		echo -e "${Yellow}1 - Network"
		echo -e "01  02a  02b  03  04  05  06  07"
		echo -e "08  09   10   11  12  13  15${Color_Off}"
		echo
		echo
		echo -e "${Green}2 - System"
		echo -e "01  02  03  04  05  06  07  08  09  10  11  12"
		echo -e "13  14  15  16  17  18  19  20  21  22  23  24${Color_Off}"
		echo
		echo -e "${UCyan}Type exit to exit${Color_Off}"
		echo
		echo -e "${UCyan}Type menu to return to main menu${Color_Off}"
		echo
		;;

		esac
		done
	else
		if [ "$selected" == "System commands" ] || [ "$selected" == "system commands" ] || [ "$selected" == "system" ] || [ "$selected" == "System" ] || [ "$selected" == "2" ] || [ "$selected" == "2 - System commands" ]; then
			echo
			echo -e "${Blue}System commands"
			echo
			echo -e "${Purple}Type a number to see the command and the output"
			echo
			echo -e "${Yellow}1 - Who am I?"
			echo
			echo -e "2 - Where am I?"
			echo
			echo -e "3 - When am I?"
			echo
			echo -e "4 - Who else is here?"
			echo
			echo -e "5 - What else is here?"
			echo
			echo -e "${UCyan}Type exit to exit${Color_Off}"
			echo
			echo -e "${UCyan}Type menu to return to main menu${Color_Off}"
			echo

			while :
			do
			read  -p "Type here: " selected
			if [ "$selected" == "exit" ]; then
				echo
				echo -e "${UCyan}Sad to see you go, bye!${Color_Off}"
				echo
				exit 1
			fi
			case "$selected" in

			"1" )
			echo
			echo -e "${Yellow}Who am I?"
			echo
			echo -e "${Green}whoami${Color_Off}"
			echo
			whoami
			echo
			;;

			"2" )
			echo
			echo -e "${Yellow}Where am I?"
			echo
			echo -e "${Green}pwd${Color_Off}"
			echo
			pwd
			echo
			;;

			"3" )
			echo
			echo -e "${Yellow}When am I?"
			echo
			echo -e "${Green}date${Color_Off}"
			echo
			date
			echo
			;;

			"4" )
			echo
			echo -e "${Yellow}Who else is here?"
			echo
			echo -e "${Green}users${Color_Off}"
			echo
			users
			echo
			;;

			"5" )
			echo
			echo -e "${Yellow}What else is here?"
			echo
			echo -e "${Green}ls${Color_Off}"
			echo
			ls
			echo
			;;

			"menu" )
			./03
			exit 1
			;;

			* )
			echo
			echo -e "${Red}Invalid command, try again!${Color_Off}"
			echo
			echo -e "${Blue}System commands"
			echo
			echo -e "${Purple}Type a number to see the command and the output"
			echo
			echo -e "${Yellow}1 - Who am I?"
			echo
			echo -e "2 - Where am I?"
			echo
			echo -e "3 - When am I?"
			echo
			echo -e "4 - Who else is here?"
			echo
			echo -e "5 - What else is here?"
			echo
			echo -e "${UCyan}Type exit to exit${Color_Off}"
			echo
			echo -e "${UCyan}Type menu to return to main menu${Color_Off}"
			echo
			;;

			esac
			done
		else
			if [ "$selected" == "A random joke" ] || [ "$selected" == "Random joke" ] || [ "$selected" == "random joke" ] || [ "$selected" == "a random joke" ] || [ "$selected" == "joke" ] || [ "$selected" == "Joke" ] || [ "$selected" == "3" ] || [ "$selected" == "3 - A random joke" ]; then
				echo
				echo -e "${IPurple}A random joke"
				echo

				while :
				do
				joke=$(( ( RANDOM % 10 )  + 1 ))
				case "$joke" in

				"1" )
				echo
				echo -e "${Green}Programming is like sex:
One mistake and you have to support it for the rest of your life.${Color_Off}"
				echo
				echo "---------------------------------"
				echo
				echo -e "${BIPurple}Choose what to do!${Color_Off}"
				echo
				echo -e "${UCyan}Type exit to exit${Color_Off}"
				echo
				echo -e "${UCyan}Type menu to return to main menu${Color_Off}"
				echo
				echo -e "${UCyan}Type anything else for another joke!${Color_Off}"
				echo
				read -p "Type here: " selected
				if [ "$selected" == "exit" ]; then
					echo
					echo -e "${UCyan}Sad to see you go, bye!${Color_Off}"
					echo
					exit 1
				else
					if [ "$selected" == "menu" ]; then
						./03
						exit 1
					else
						echo
						echo -e "${Red}ANOTHER RANDOM JOKE!${Color_Off}"
						echo
					fi
				fi
				;;

				"2" )
				echo
				echo -e "${Green}How did the programmer die in the shower?
He read the shampoo bottle instructions: Lather. Rinse. Repeat.${Color_Off}"
				echo
				echo "---------------------------------"
				echo
				echo -e "${BIPurple}Choose what to do!${Color_Off}"
				echo
				echo -e "${UCyan}Type exit to exit${Color_Off}"
				echo
				echo -e "${UCyan}Type menu to return to main menu${Color_Off}"
				echo
				echo -e "${UCyan}Type anything else for another joke!${Color_Off}"
				echo
				read -p "Type here: " selected
				if [ "$selected" == "exit" ]; then
					echo
					echo -e "${UCyan}Sad to see you go, bye!${Color_Off}"
					echo
					exit 1
				else
					if [ "$selected" == "menu" ]; then
						./03
						exit 1
					else
						echo
						echo -e "${Red}ANOTHER RANDOM JOKE!${Color_Off}"
						echo
					fi
				fi
				;;

				"3" )
				echo
				echo -e "${Green}A man is smoking a cigarette and blowing smoke rings into the air.
His girlfriend becomes irritated with the smoke and says,
“Can’t you see the warning on the cigarette pack? Smoking is hazardous to your health!”

To which the man replies, “I am a programmer.
We don’t worry about warnings; we only worry about errors.”${Color_Off}"
				echo
				echo "---------------------------------"
				echo
				echo -e "${BIPurple}Choose what to do!${Color_Off}"
				echo
				echo -e "${UCyan}Type exit to exit${Color_Off}"
				echo
				echo -e "${UCyan}Type menu to return to main menu${Color_Off}"
				echo
				echo -e "${UCyan}Type anything else for another joke!${Color_Off}"
				echo
				read -p "Type here: " selected
				if [ "$selected" == "exit" ]; then
					echo
					echo -e "${UCyan}Sad to see you go, bye!${Color_Off}"
					echo
					exit 1
				else
					if [ "$selected" == "menu" ]; then
						./03
						exit 1
					else
						echo
						echo -e "${Red}ANOTHER RANDOM JOKE!${Color_Off}"
						echo
					fi
				fi
				;;

				"4" )
				echo
				echo -e "${Green}Two strings walk into a bar and sit down. The bartender says, “So what’ll it be?”
The first string says, “I think I’ll have a beer quag fulk boorg jdk^CjfdLk jk3s d#f67howe%^U r89nvy~~owmc63^Dz x.xvcu”

“Please excuse my friend,” the second string says, “He isn’t null-terminated.”${Color_Off}"
				echo
				echo "---------------------------------"
				echo
				echo -e "${BIPurple}Choose what to do!${Color_Off}"
				echo
				echo -e "${UCyan}Type exit to exit${Color_Off}"
				echo
				echo -e "${UCyan}Type menu to return to main menu${Color_Off}"
				echo
				echo -e "${UCyan}Type anything else for another joke!${Color_Off}"
				echo
				read -p "Type here: " selected
				if [ "$selected" == "exit" ]; then
					echo
					echo -e "${UCyan}Sad to see you go, bye!${Color_Off}"
					echo
					exit 1
				else
					if [ "$selected" == "menu" ]; then
						./03
						exit 1
					else
						echo
						echo -e "${Red}ANOTHER RANDOM JOKE!${Color_Off}"
						echo
					fi
				fi
				;;

				"5" )
				echo
				echo -e "${Green}There are only 10 kinds of people in this world:
those who know binary and those who don’t.${Color_Off}"
				echo
				echo "---------------------------------"
				echo
				echo -e "${BIPurple}Choose what to do!${Color_Off}"
				echo
				echo -e "${UCyan}Type exit to exit${Color_Off}"
				echo
				echo -e "${UCyan}Type menu to return to main menu${Color_Off}"
				echo
				echo -e "${UCyan}Type anything else for another joke!${Color_Off}"
				echo
				read -p "Type here: " selected
				if [ "$selected" == "exit" ]; then
					echo
					echo -e "${UCyan}Sad to see you go, bye!${Color_Off}"
					echo
					exit 1
				else
					if [ "$selected" == "menu" ]; then
						./03
						exit 1
					else
						echo
						echo -e "${Red}ANOTHER RANDOM JOKE!${Color_Off}"
						echo
					fi
				fi
				;;

				"6" )
				echo
				echo -e "${Green}What is the most used language in programming?
Profanity.${Color_Off}"
				echo
				echo "---------------------------------"
				echo
				echo -e "${BIPurple}Choose what to do!${Color_Off}"
				echo
				echo -e "${UCyan}Type exit to exit${Color_Off}"
				echo
				echo -e "${UCyan}Type menu to return to main menu${Color_Off}"
				echo
				echo -e "${UCyan}Type anything else for another joke!${Color_Off}"
				echo
				read -p "Type here: " selected
				if [ "$selected" == "exit" ]; then
					echo
					echo -e "${UCyan}Sad to see you go, bye!${Color_Off}"
					echo
					exit 1
				else
					if [ "$selected" == "menu" ]; then
						./03
						exit 1
					else
						echo
						echo -e "${Red}ANOTHER RANDOM JOKE!${Color_Off}"
						echo
					fi
				fi
				;;

				"7" )
				echo
				echo -e "${Green}Programmer: Honey, you are my number one
Wife: Oh, really!? Well who is your number zero, you cheating bastard!?${Color_Off}"
				echo
				echo "---------------------------------"
				echo
				echo -e "${BIPurple}Choose what to do!${Color_Off}"
				echo
				echo -e "${UCyan}Type exit to exit${Color_Off}"
				echo
				echo -e "${UCyan}Type menu to return to main menu${Color_Off}"
				echo
				echo -e "${UCyan}Type anything else for another joke!${Color_Off}"
				echo
				read -p "Type here: " selected
				if [ "$selected" == "exit" ]; then
					echo
					echo -e "${UCyan}Sad to see you go, bye!${Color_Off}"
					echo
					exit 1
				else
					if [ "$selected" == "menu" ]; then
						./03
						exit 1
					else
						echo
						echo -e "${Red}ANOTHER RANDOM JOKE!${Color_Off}"
						echo
					fi
				fi
				;;

				"8" )
				echo
				echo -e "${Green}A wife asks her programmer husband to go to the store
'Can you go down to the store, and get a gallon of milk, and if they have eggs, get 6.'

Later on he returns home and she looks at his
purchases and says 'Why the fuck do you have 6 gallons of milk?'

He responded 'They had eggs.'${Color_Off}"
				echo
				echo "---------------------------------"
				echo
				echo -e "${BIPurple}Choose what to do!${Color_Off}"
				echo
				echo -e "${UCyan}Type exit to exit${Color_Off}"
				echo
				echo -e "${UCyan}Type menu to return to main menu${Color_Off}"
				echo
				echo -e "${UCyan}Type anything else for another joke!${Color_Off}"
				echo
				read -p "Type here: " selected
				if [ "$selected" == "exit" ]; then
					echo
					echo -e "${UCyan}Sad to see you go, bye!${Color_Off}"
					echo
					exit 1
				else
					if [ "$selected" == "menu" ]; then
						./03
						exit 1
					else
						echo
						echo -e "${Red}ANOTHER RANDOM JOKE!${Color_Off}"
						echo
					fi
				fi
				;;

				"9" )
				echo
				echo -e "${Green}How programmers and cats are alike?
They both can sit in the same position for long time and get excited when they find a bug${Color_Off}"
				echo
				echo "---------------------------------"
				echo
				echo -e "${BIPurple}Choose what to do!${Color_Off}"
				echo
				echo -e "${UCyan}Type exit to exit${Color_Off}"
				echo
				echo -e "${UCyan}Type menu to return to main menu${Color_Off}"
				echo
				echo -e "${UCyan}Type anything else for another joke!${Color_Off}"
				echo
				read -p "Type here: " selected
				if [ "$selected" == "exit" ]; then
					echo
					echo -e "${UCyan}Sad to see you go, bye!${Color_Off}"
					echo
					exit 1
				else
					if [ "$selected" == "menu" ]; then
						./03
						exit 1
					else
						echo
						echo -e "${Red}ANOTHER RANDOM JOKE!${Color_Off}"
						echo
					fi
				fi
				;;

				"10" )
				echo
				echo -e "${Green}A programmer walked into a bar.
He raised his middle finger and his thumb to the bartender and said: 5 beers please.${Color_Off}"
				echo
				echo "---------------------------------"
				echo
				echo -e "${BIPurple}Choose what to do!${Color_Off}"
				echo
				echo -e "${UCyan}Type exit to exit${Color_Off}"
				echo
				echo -e "${UCyan}Type menu to return to main menu${Color_Off}"
				echo
				echo -e "${UCyan}Type anything else for another joke!${Color_Off}"
				echo
				read -p "Type here: " selected
				if [ "$selected" == "exit" ]; then
					echo
					echo -e "${UCyan}Sad to see you go, bye!${Color_Off}"
					echo
					exit 1
				else
					if [ "$selected" == "menu" ]; then
						./03
						exit 1
					else
						echo
						echo -e "${Red}ANOTHER RANDOM JOKE!${Color_Off}"
						echo
					fi
				fi
				;;

				esac
				done
			else
				echo
				echo -e "${Red}Invalid command, try again!${Color_Off}"
				echo
			fi
		fi
	fi
fi
done